version: '3.7'

services:
  postgres-api:
    image: postgres
    container_name: postgres-api
    volumes:
      - './configs/db/postgres:/var/lib/postgresql/data'
    networks:
      - api-sippe
    environment:
      - POSTGRES_DB=sippe
      - POSTGRES_USER=sippe
      - POSTGRES_PASSWORD=sippe2023
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "sippe"]
      interval: 5s
      timeout: 10s
      retries: 3

  django-api:
    build:
      context: .
      dockerfile: Dockerfile.Django
    container_name: django-api
    #entrypoint: [ "/entrypoint.sh" ]
    networks:
      - api-sippe
    volumes:
      - ./:/api
    ports:
      - "8000:8000"
    environment:
      - PGDATABASE=sippe
      - PGUSER=sippe
      - PGPASSWORD=sippe2023
      - PGHOST=postgres-api
      - PGPORT=5432
      - MYSECRET=insecure-v@f)l361(joj_3-ie-^=)r$rvv3d1l_v&2%o*_gf^dp*_%zb^8*¨%987GBJHGouY¨()*&%897gcybsa098d7c568
      - MYDEBUG=False
    depends_on:
      postgres-api:
        condition: service_healthy
    #restart: always

    
networks:
  api-sippe:
    driver: bridge
